 manifest:
    remotes:
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
        - name: m165437
          url-base: https://github.com/M165437
        - name: gpeye
          url-base: https://github.com/GPeye
        - name: tokyo2006
          url-base: https://github.com/tokyo2006
        - name: englmaxi
          url-base: https://github.com/englmaxi
        - name: nexus
          url-base: https://github.com/vaibhav8600-rgb
    projects:
        - name: zmk
          remote: zmkfirmware
          revision: v0.3
          import: app/west.yml
        - name: nice-view-gem
          remote: m165437
          revision: v0.3.0
        - name: zmk-dongle-display
          remote: englmaxi
          revision: v0.3
        - name: nexus
          remote: nexus          # url-base: https://github.com/vaibhav8600-rgb
          revision: v1.0.0
    self:
        path: config
